import "./globals.css";
import NavBar from "@/components/AuthNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">

        {/* // relode problem */}
        {/* <div className="flex gap-6">
          <a href="/home">Home</a>
          <a href="/about">About</a>
          <a href="/contact">Contact</a>
        </div> */}
        {/* <NavBar/> */}

        {children}
      </body>
    </html>
  );
}
